"""FitGround configuration constants."""

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "data"
RAW_FIT_DIR = DATA_DIR / "raw" / "fit"
INTERIM_DIR = DATA_DIR / "interim"
HF_CACHE_DIR = DATA_DIR / "cache" / "huggingface"
FIT_CHECKPOINT_DIR = INTERIM_DIR / "fit_checkpoint"
PROCESSED_DIR = DATA_DIR / "processed"
REPORTS_DIR = PROJECT_ROOT / "reports"
FIGURES_DIR = REPORTS_DIR / "figures"

HF_REPO_ID = "Yuanhao-Harry-Wang/fitvto-100k"
HF_SOURCE_REVISION = "5563646729edf148ed2b32c4b9c794d51a1bc828"
SOURCE_DATASET = "fitvto-100k"
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"
DOCS_DIR = PROJECT_ROOT / "docs"
MANIFEST_VERSION = "v0.1"
MANIFEST_PATH = PROCESSED_DIR / f"fit_clean_{MANIFEST_VERSION}.parquet"
EVAL_MANIFEST_PATH = PROCESSED_DIR / "fit_eval_clean_v0.1.parquet"
EVAL_CHECKPOINT_DIR = INTERIM_DIR / "eval_checkpoint"
DEFAULT_IMAGE_BATCH_SIZE = 8
MAX_IMAGE_BATCH_SIZE = 16
RSS_LIMIT_BYTES = int(1.5 * 1024**3)

TRAIN_SHARD_COUNT = 406
EVAL_SHARD_COUNT = 20

# Body measurement plausible ranges (cm) — INVALID if outside hard bounds.
BODY_HEIGHT_CM_MIN = 120.0
BODY_HEIGHT_CM_MAX = 230.0
BODY_BUST_CM_MIN = 60.0
BODY_BUST_CM_MAX = 180.0
BODY_WAIST_CM_MIN = 50.0
BODY_WAIST_CM_MAX = 180.0
BODY_HIPS_CM_MIN = 60.0
BODY_HIPS_CM_MAX = 200.0

GARMENT_BUST_CM_MIN = 50.0
GARMENT_BUST_CM_MAX = 250.0
GARMENT_LENGTH_CM_MIN = 10.0
GARMENT_LENGTH_CM_MAX = 200.0
GARMENT_SLEEVE_CM_MIN = 0.0
GARMENT_SLEEVE_CM_MAX = 100.0

EXPECTED_IMAGE_WIDTH = 768
EXPECTED_IMAGE_HEIGHT = 1024

# SUSPICIOUS thresholds (not INVALID — extreme fit is valid research signal).
BUST_EASE_CM_SUSPICIOUS_LOW = -30.0
BUST_EASE_CM_SUSPICIOUS_HIGH = 60.0
BUST_EASE_RATIO_SUSPICIOUS_LOW = -0.25
BUST_EASE_RATIO_SUSPICIOUS_HIGH = 0.55

# Dataset size from HF README metadata (bytes).
DATASET_TRAIN_BYTES = 202_588_693_900
DATASET_EVAL_BYTES = 9_997_680_005
DATASET_TOTAL_BYTES = 212_586_373_905
